import { useState } from "react";
import { useAuth } from "../lib/auth";

function initials(name = "") {
  return name.split(" ").map(n => n[0]).join("").slice(0,2).toUpperCase();
  }

  const TABS = [
    { id:"tasks",    label:"Tareas" },
      { id:"schedule", label:"Turno" },
        { id:"requests", label:"Solicitudes" },
        ];

        function Placeholder({ label }) {
          return (
              <div style={{ padding:24, color:"var(--color-muted)", fontFamily:"var(--font-cond)", fontSize:".72rem", letterSpacing:".15em", textTransform:"uppercase" }}>
                    {label}
                        </div>
                          );
                          }

                          export default function CommisLayout() {
                            const { profile, signOut } = useAuth();
                              const [tab, setTab] = useState("tasks");

                                return (
                                    <div style={{ minHeight:"100vh", display:"grid", gridTemplateRows:"auto 1fr", maxWidth:430, margin:"0 auto" }}>

                                          <div style={{ background:"var(--color-ink-1)", borderBottom:"1px solid var(--color-ink-4)", padding:"10px 16px" }}>
                                                  <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:10 }}>
                                                            <div style={{ display:"flex", alignItems:"center", gap:10 }}>
                                                                        <div style={{ width:32, height:32, background:"var(--color-ember-dim)", display:"flex", alignItems:"center", justifyContent:"center", fontFamily:"var(--font-cond)", fontSize:".72rem", fontWeight:700, color:"var(--color-ember)", textTransform:"uppercase" }}>
                                                                                      {initials(profile?.full_name)}
                                                                                                  </div>
                                                                                                              <div>
                                                                                                                            <div style={{ fontFamily:"var(--font-cond)", fontSize:".88rem", fontWeight:600, letterSpacing:".06em", textTransform:"uppercase" }}>
                                                                                                                                            {profile?.full_name}
                                                                                                                                                          </div>
                                                                                                                                                                        <div style={{ fontFamily:"var(--font-cond)", fontSize:".58rem", letterSpacing:".12em", textTransform:"uppercase", color:"var(--color-muted)" }}>
                                                                                                                                                                                        {profile?.role}
                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                      <button onClick={signOut} style={{ background:"none", border:"1px solid var(--color-ink-4)", color:"var(--color-muted)", fontFamily:"var(--font-cond)", fontSize:".6rem", letterSpacing:".12em", textTransform:"uppercase", padding:"4px 10px", cursor:"pointer" }}>
                                                                                                                                                                                                                                                  Salir
                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                            <div style={{ display:"flex", borderTop:"1px solid var(--color-ink-4)", marginLeft:-16, marginRight:-16 }}>
                                                                                                                                                                                                                                                                                      {TABS.map(t => (
                                                                                                                                                                                                                                                                                                  <button key={t.id} onClick={() => setTab(t.id)} style={{
                                                                                                                                                                                                                                                                                                                flex:1, padding:"9px 4px",
                                                                                                                                                                                                                                                                                                                              fontFamily:"var(--font-cond)", fontSize:".65rem", letterSpacing:".12em",
                                                                                                                                                                                                                                                                                                                                            textTransform:"uppercase", border:"none", background:"none", cursor:"pointer",
                                                                                                                                                                                                                                                                                                                                                          borderBottom: tab===t.id ? "2px solid var(--color-ember)" : "2px solid transparent",
                                                                                                                                                                                                                                                                                                                                                                        color: tab===t.id ? "var(--color-ember)" : "var(--color-muted)",
                                                                                                                                                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                                                                                                                                                                  {t.label}
                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ overflow:"auto" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {tab==="tasks"    && <Placeholder label="Tareas — conectando…" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {tab==="schedule" && <Placeholder label="Turno — conectando…" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {tab==="requests" && <Placeholder label="Solicitudes — conectando…" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }