import { useState, useEffect } from "react";
import { supabase } from "../lib/supabase";
import { useAuth } from "../lib/auth";

const STATUS_COLOR = {
  done:        "var(--color-success)",
    in_progress: "var(--color-info)",
      blocked:     "var(--color-danger)",
        pending:     "var(--color-muted)",
          problem:     "var(--color-warn)",
          };

          export default function TasksDashboard() {
            const { profile } = useAuth();
              const [events,  setEvents]  = useState([]);
                const [tasks,   setTasks]   = useState([]);
                  const [loading, setLoading] = useState(true);

                    useEffect(() => {
                        loadData();
                            const ch = supabase.channel("public:tasks")
                                  .on("*", {}, () => loadData())
                                        .subscribe();
                                            return () => ch.unsubscribe();
                                              }, []);

                                                async function loadData() {
                                                    const { data: evs } = await supabase.select("events", {
                                                          order: "event_date.asc", limit: 5,
                                                              });
                                                                  setEvents(evs || []);
                                                                      if (evs?.length) {
                                                                            const { data: tks } = await supabase.select("tasks", {
                                                                                    filters: { event_id: evs[0].id },
                                                                                            order: "sort_order.asc",
                                                                                                  });
                                                                                                        setTasks(tks || []);
                                                                                                            }
                                                                                                                setLoading(false);
                                                                                                                  }

                                                                                                                    async function updateStatus(taskId, newStatus) {
                                                                                                                        await supabase.update("tasks", { status: newStatus }, { id: taskId });
                                                                                                                            loadData();
                                                                                                                              }

                                                                                                                                async function createTestEvent() {
                                                                                                                                    const { data: org } = await supabase.select("organizations", { limit:1, single:true });
                                                                                                                                        await supabase.insert("events", {
                                                                                                                                              org_id: org.id, name:"Evento de prueba",
                                                                                                                                                    event_date:"2026-06-01", pax:20,
                                                                                                                                                          status:"draft", created_by: profile.id,
                                                                                                                                                              });
                                                                                                                                                                  loadData();
                                                                                                                                                                    }

                                                                                                                                                                      if (loading) return (
                                                                                                                                                                          <div style={{ padding:24, color:"var(--color-muted)", fontFamily:"var(--font-cond)", fontSize:".72rem", letterSpacing:".15em", textTransform:"uppercase" }}>
                                                                                                                                                                                Cargando…
                                                                                                                                                                                    </div>
                                                                                                                                                                                      );

                                                                                                                                                                                        if (!events.length) return (
                                                                                                                                                                                            <div style={{ padding:24 }}>
                                                                                                                                                                                                  <div style={{ color:"var(--color-muted)", fontFamily:"var(--font-cond)", fontSize:".72rem", letterSpacing:".15em", textTransform:"uppercase", marginBottom:16 }}>
                                                                                                                                                                                                          Sin eventos — creá uno para empezar
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                      <button onClick={createTestEvent} style={{ fontFamily:"var(--font-cond)", fontSize:".65rem", letterSpacing:".14em", textTransform:"uppercase", padding:"8px 20px", border:"1px solid var(--color-ember-dim)", color:"var(--color-ember)", background:"var(--color-ember-bg)", cursor:"pointer" }}>
                                                                                                                                                                                                                              + Crear evento de prueba
                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                            const event = events[0];
                                                                                                                                                                                                                                              const byPhase = { "D-2":[], "D-1":[], "D-0":[] };
                                                                                                                                                                                                                                                tasks.forEach(t => { if (byPhase[t.phase]) byPhase[t.phase].push(t); });
                                                                                                                                                                                                                                                  const done = tasks.filter(t => t.status==="done").length;
                                                                                                                                                                                                                                                    const pct  = tasks.length ? Math.round(done/tasks.length*100) : 0;

                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                          <div style={{ height:"100%", overflow:"auto" }}>

                                                                                                                                                                                                                                                                <div style={{ padding:"16px 20px", background:"var(--color-ink-1)", borderBottom:"1px solid var(--color-ink-4)" }}>
                                                                                                                                                                                                                                                                        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                              <div style={{ fontFamily:"var(--font-cond)", fontSize:"1.1rem", fontWeight:700, letterSpacing:".06em", textTransform:"uppercase" }}>
                                                                                                                                                                                                                                                                                                            {event.name}
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                    <div style={{ fontFamily:"var(--font-cond)", fontSize:".65rem", letterSpacing:".1em", textTransform:"uppercase", color:"var(--color-muted)", marginTop:3 }}>
                                                                                                                                                                                                                                                                                                                                                  {event.event_date} · {event.pax} pax
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontFamily:"var(--font-cond)", fontSize:"1.8rem", fontWeight:700, color:"var(--color-ember)" }}>
                                                                                                                                                                                                                                                                                                                                                                                              {pct}%
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ height:2, background:"var(--color-ink-4)", marginTop:10, borderRadius:1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ height:"100%", background:"var(--color-ember)", width:`${pct}%`, borderRadius:1, transition:"width .5s" }}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ padding:16, display:"flex", flexDirection:"column", gap:16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {Object.entries(byPhase).map(([phase, phaseTasks]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={phase}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontFamily:"var(--font-cond)", fontSize:".65rem", fontWeight:700, letterSpacing:".2em", textTransform:"uppercase", color:"var(--color-ember)", marginBottom:8, display:"flex", alignItems:"center", gap:10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {phase}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ flex:1, height:1, background:"var(--color-ink-4)" }}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ color:"var(--color-muted)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {phaseTasks.filter(t=>t.status==="done").length}/{phaseTasks.length}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {phaseTasks.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontFamily:"var(--font-cond)", fontSize:".6rem", letterSpacing:".12em", textTransform:"uppercase", color:"var(--color-ink-5)", padding:"8px 0" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Sin tareas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {phaseTasks.map(task => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={task.id} style={{ background:"var(--color-ink-1)", border:"1px solid var(--color-ink-4)", borderLeft:`3px solid ${STATUS_COLOR[task.status]||"var(--color-ink-5)"}`, padding:"10px 12px", marginBottom:4, display:"flex", alignItems:"center", gap:10, opacity:task.status==="done"?.5:1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ flex:1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontFamily:"var(--font-cond)", fontSize:".82rem", fontWeight:500, letterSpacing:".04em", textTransform:"uppercase" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {task.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontFamily:"var(--font-cond)", fontSize:".58rem", letterSpacing:".1em", textTransform:"uppercase", color:"var(--color-muted)", marginTop:2 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {task.status} · {task.priority}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display:"flex", gap:4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {task.status==="pending" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => updateStatus(task.id,"in_progress")} style={{ fontFamily:"var(--font-cond)", fontSize:".58rem", letterSpacing:".1em", textTransform:"uppercase", padding:"4px 10px", border:"1px solid #1a3a50", color:"var(--color-info)", background:"none", cursor:"pointer" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Iniciar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {task.status==="in_progress" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => updateStatus(task.id,"done")} style={{ fontFamily:"var(--font-cond)", fontSize:".58rem", letterSpacing:".1em", textTransform:"uppercase", padding:"4px 10px", border:"1px solid #1a4a2a", color:"var(--color-success)", background:"none", cursor:"pointer" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Completar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }